version: 2

sources:
  - name: bronze
    description: "Pre-existing bronze layer tables in Databricks (external to dbt)"
    database: airbnb_medallion
    schema: airbnb_bronze
    tables:
      - name: listings
        description: "Raw Airbnb listings data (created by external Databricks notebook)"
        columns:
          - name: id
            description: "Unique listing identifier"
            tests:
              - unique
              - not_null
          - name: host_id
            description: "Host identifier"
          - name: price
            description: "Price per night as string"
          - name: last_review
            description: "Date of last review"

      - name: reviews
        description: "Raw Airbnb reviews data (created by external Databricks notebook)"
        columns:
          - name: listing_id
            description: "Reference to listing"
          - name: id
            description: "Unique review identifier"
            tests:
              - unique
              - not_null
          - name: date
            description: "Review date"

      - name: seed_full_moon_dates
        description: "Full moon dates (managed by dbt seed)"
        columns:
          - name: date
            description: "Full moon date"
            tests:
              - unique
              - not_null
